# Amazon-Reviews-2023

# Main categories:
# - Sports_and_Outdoors
# - Beauty
# - Toys_and_Games

train:
  _target_: src.datasets.AmazonReviewsDataset
  part: "train"
  category: "Sports_and_Outdoors"

  leave_one_out: true
  min_history_length: 2               # 滑窗最短history长度（含label前的序列长度）
  max_history_length: 50              # 滑窗最长history长度（与max_history_len对齐）

val:
  _target_: src.datasets.AmazonReviewsDataset
  part: "val"
  category: "Sports_and_Outdoors"

  leave_one_out: true
  min_history_length: 2               # 滑窗最短history长度（含label前的序列长度）
  max_history_length: 50              # 滑窗最长history长度（与max_history_len对齐）
